import { NextResponse } from 'next/server';
import { WorkoutPlan } from '@/types/workout-planner';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { userId } = body;

    // Mock workout plan generation
    const plan: WorkoutPlan = {
      id: Math.random().toString(36).substr(2, 9),
      userId,
      name: 'AI-Generated Full Body Workout',
      description: 'A balanced full-body workout generated by AI.',
      difficulty: 'intermediate',
      duration: 45,
      exercises: [
        {
          exercise: {
            id: '1',
            name: 'Barbell Squat',
            description: 'A compound exercise that targets the lower body.',
            muscleGroup: 'legs',
            difficulty: 'intermediate',
            equipment: ['barbell', 'squat rack'],
            instructions: [
              'Position the bar on your upper back',
              'Stand with feet shoulder-width apart',
              'Lower until thighs are parallel to ground',
              'Push through heels to return to start'
            ]
          },
          sets: 3,
          reps: 10,
          restTime: 60
        },
        {
          exercise: {
            id: '2',
            name: 'Bench Press',
            description: 'A compound exercise that targets the chest.',
            muscleGroup: 'chest',
            difficulty: 'intermediate',
            equipment: ['barbell', 'bench'],
            instructions: [
              'Lie on the bench',
              'Grip the bar slightly wider than shoulder-width',
              'Lower the bar to your chest',
              'Push the bar back up to the starting position'
            ]
          },
          sets: 3,
          reps: 10,
          restTime: 60
        }
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    return NextResponse.json(plan);
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to generate workout plan' },
      { status: 500 }
    );
  }
} 